const PLAN = {
  title: "蕾蕾working space",
  subtitle: "ClickUp social media calendar",
  source: "ClickUp · Jason's Space · 蕾蕾working space",
  timezone: "Asia/Hong_Kong",
  parentId: "86eycec06",
  parentUrl: "https://sharing.clickup.com/25623340/t/h/86eycec06/70EHIF2B71A5FQW",
  syncedAt: "2026-09-01T16:14:00+08:00",
  note: "All dates shifted +7 days from original ClickUp schedule",
  posts: [
    {
      id: "86eyr3rnm",
      number: 1,
      title: "Jason創業故事",
      target: "IP Development",
      postTarget: "建立外介對Jason的信任度",
      status: "in progress",
      priority: "High",
      shooting: "",
      submission: "2026-08-31",
      publish: "2026-09-03",
      content:
        "1：Target: IP Development | Post Target: 建立外介對Jason的信任度 | 《Jason創業故事》 | Submission Date: 31 Aug, Publish Date: 3 Sept",
      url: "https://sharing.clickup.com/25623340/t/h/86eyr3rnm/70EHIF2B71A5FQW",
    },
    {
      id: "86eyr69fg",
      number: 2,
      title: "60秒介紹SSF場地",
      target: "Studio Environment",
      postTarget: "Engage New Clients",
      status: "in progress",
      priority: "High",
      shooting: "",
      submission: "2026-08-31",
      publish: "2026-09-04",
      content:
        "2：Target: Studio Environment | Post Target: Engage New Clients | 《60秒介紹SSF場地》 | Submission Date: 31 Aug, Publish Date: 4 Sept",
      url: "https://sharing.clickup.com/25623340/t/h/86eyr69fg/70EHIF2B71A5FQW",
    },
    {
      id: "86eyr6h8y",
      number: 3,
      title: "SSF Training Style - Commercial Vibe落AD片",
      target: "Brand Image Building",
      postTarget: "Engage New Clients 等新客理解SSF Vibe同理念",
      status: "to do",
      priority: "",
      shooting: "",
      submission: "2026-09-04",
      publish: "2026-09-10",
      content:
        "3：Target: Brand Image Building | Post Target: Engage New Clients 等新客理解SSF Vibe同理念 | 《SSF Training Style - Commercial Vibe落AD片》 | Submission Date: 4 Sept, Publish Date: 10 Sept",
      url: "https://sharing.clickup.com/25623340/t/h/86eyr6h8y/70EHIF2B71A5FQW",
    },
    {
      id: "86eyr6h9t",
      number: 4,
      title: "練Hyrox必經Transformation",
      target: "Group Class Training",
      postTarget: "Attract People to Join Hyrox Group",
      status: "to do",
      priority: "",
      shooting: "",
      submission: "2026-09-07",
      publish: "2026-09-14",
      content:
        "4：Target: Group Class Training | Post Target: Attract People to Join Hyrox Group | 《練Hyrox必經Transformation》 | Submission Date: 7 Sept, Publish Date: 14 Sept",
      url: "https://sharing.clickup.com/25623340/t/h/86eyr6h9t/70EHIF2B71A5FQW",
    },
    {
      id: "86eyr6hb0",
      number: 5,
      title: "你真係Train緊Core？",
      target: "IP Development",
      postTarget: "建立外介對Jason的信任度",
      status: "to do",
      priority: "",
      shooting: "",
      submission: "2026-09-10",
      publish: "2026-09-17",
      content:
        "5：Target: IP Development | Post Target: 建立外介對Jason的信任度 | 《你真係Train緊Core？》 | Submission Date: 10 Sept, Publish Date: 17 Sept",
      url: "https://sharing.clickup.com/25623340/t/h/86eyr6hb0/70EHIF2B71A5FQW",
    },
    {
      id: "86eyr6hbu",
      number: 6,
      title: "同學生建立「Common Language」",
      target: "IP Development",
      postTarget: "展示Jason教學方法",
      status: "to do",
      priority: "",
      shooting: "",
      submission: "2026-09-10",
      publish: "2026-09-22",
      content:
        "6：Target: IP Development | Post Target: 展示Jason教學方法 | 《同學生建立「Common Language」》 | Submission Date: 10 Sept, Publish Date: 22 Sept",
      url: "https://sharing.clickup.com/25623340/t/h/86eyr6hbu/70EHIF2B71A5FQW",
    },
    {
      id: "86eyr6hck",
      number: 7,
      title: "點解要記低訓練數據？",
      target: "IP Development & Brand Image Building",
      postTarget: "Prove到比人睇訓練係基於數據",
      status: "to do",
      priority: "",
      shooting: "",
      submission: "2026-09-16",
      publish: "2026-09-25",
      content:
        "7：Target: IP Development & Brand Image Building | Post Target: Prove到比人睇訓練係基於數據 | 《點解要記低訓練數據？》 | Submission Date: 16 Sept, Publish Date: 25 Sept",
      url: "https://sharing.clickup.com/25623340/t/h/86eyr6hck/70EHIF2B71A5FQW",
    },
    {
      id: "86eyr6hdf",
      number: 8,
      title: "學生分享",
      target: "Brand Image Building",
      postTarget: "等外界知道學生質素係運動員 / 長者",
      status: "to do",
      priority: "",
      shooting: "",
      submission: "",
      publish: "2026-09-30",
      content:
        "8：Target: Brand Image Building | Post Target: 等外界知道學生質素係運動員 / 長者 | 《學生分享》 | Submission Date: TBC, Publish Date: 30 Sept",
      url: "https://sharing.clickup.com/25623340/t/h/86eyr6hdf/70EHIF2B71A5FQW",
    },
    {
      id: "86eyr6heg",
      number: 9,
      title: "Nora 解釋點解要做 Mobility 相關嘅動作？",
      target: "Brand Image Building",
      postTarget: "Engage New Clients",
      status: "to do",
      priority: "",
      shooting: "2026-09-21",
      submission: "2026-09-25",
      publish: "2026-09-30",
      content:
        "9：Target: Brand Image Building | Post Target: Engage New Clients | 《Nora 解釋點解要做 Mobility 相關嘅動作？》 | Shooting Date: 21 Sept, Submission Date: 25 Sept, Publish Date: 30 Sept",
      url: "https://sharing.clickup.com/25623340/t/h/86eyr6heg/70EHIF2B71A5FQW",
    },
    {
      id: "86eyr6hgd",
      number: 10,
      title: "I仔玩健身",
      target: "Brand Image Building",
      postTarget: "Engage New Clients",
      status: "to do",
      priority: "",
      shooting: "2026-09-21",
      submission: "2026-09-29",
      publish: "2026-10-06",
      content:
        "10：Target: Brand Image Building | Post Target: Engage New Clients | 《I仔玩健身》 | Shooting Date: 21 Sept, Submission Date: 29 Sept, Publish Date: 6 Oct",
      url: "https://sharing.clickup.com/25623340/t/h/86eyr6hgd/70EHIF2B71A5FQW",
    },
  ],
};
